### PR TITLE
fix case of dictionary column as path for JSON lookup

### LINKED ISSUE #53: Error raised while using a column as a JSON access key
Using logfire, I ran into the following bug.

The query:
```sql
SELECT otel_events->>0->>attributes FROM records
```
The error message:
```
Error: Internal error: UDF returned a different number of rows than expected. Expected: 29, Got: 11. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```
I think the issue is that there is something not properly handled when the operator has a column on the right. I know there are tests of this so it's probably not something super obvious, maybe the composition is necessary to reproduce the issue, or maybe it has something to do with how the data has been serialized into row groups, etc.

Let me know if you have trouble reproducing.

### PR DESCRIPTION
**Pull request by davidhewitt**
Fixes #53

The logic was wrong; we were pulling out the dictionary values and then zipping on that, which was just mixing up data and generally incorrect.

### CODE REVIEW

File: tests/utils/mod.rs [hunk 1]
```diff
@@ -96,7 +96,11 @@ async fn create_test_table(large_utf8: bool, dict_encoded: bool) -> Result<Sessi
         Arc::new(Schema::new(vec![
             Field::new("json_data", DataType::Utf8, false),
             Field::new("str_key1", DataType::Utf8, false),
-            Field::new("str_key2", DataType::Utf8, false),
+            Field::new(
```
Comment (davidhewitt) [inline tests/utils/mod.rs:99]: With this change to the test suite and not the corresponding changes to `common.rs`, the issue in #53 reproduced as part of the suite.

**Review by samuelcolvin — COMMENTED** [review]
Honestly, this is beyond my capacity to review right now, but I trust you.
